<?php
//Released on Oct. 11 2008

if( ! defined( 'XOOPS_ROOT_PATH' ) ) exit ;
$mydirname = basename( dirname( __FILE__ ) ) ;
$cloned_lang =  '_MI_' . strtoupper( $mydirname ) ;


$modversion['name'] = _MI_ALUMNI_NAME;
$modversion['version'] = '3.0 BETA1';
$modversion['description'] = _MI_ALUMNI_DESC;
$modversion['credits'] = "Alumni Module for Xoops by John Mordo Created from Myads jp 2.04";
$modversion['author'] = "John Mordo - user jlm69 on Xoops";
$modversion['license'] = "GPL";
$modversion['official'] = 0;
$modversion['image'] = "images/alumni_slogo.gif";
$modversion['dirname'] = "$mydirname";

// Admin things
$modversion['hasAdmin'] = 1;
$modversion['adminindex'] = "admin/index.php";
$modversion['adminmenu'] = "admin/menu.php";

// Templates
$modversion['templates'][1]['file'] = "".$mydirname."_index.html";
$modversion['templates'][1]['description'] = '';
$modversion['templates'][2]['file'] = "".$mydirname."_adlist.html";
$modversion['templates'][2]['description'] = '';
$modversion['templates'][3]['file'] = "".$mydirname."_category.html";
$modversion['templates'][3]['description'] = '';
$modversion['templates'][4]['file'] = "".$mydirname."_item.html";
$modversion['templates'][4]['description'] = '';

// Blocks
$modversion['blocks'][1]['file'] = "alumni.php";
$modversion['blocks'][1]['name'] = _MI_ALUMNI_BNAME . " ($mydirname)";
$modversion['blocks'][1]['description'] = _MI_ALUMNI_BNAME_DESC;
$modversion['blocks'][1]['show_func'] = "".$mydirname."_show";
$modversion['blocks'][1]['template'] = "".$mydirname."_block_new.html";
$modversion['blocks'][1]['can_clone'] = "true" ;
$modversion['blocks'][1]['options'] = "{$mydirname}";

// Menu
$modversion['hasMain'] = 1;

// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
// All tables should not have any prefix!
$modversion['sqlfile']['mysql'] = "sql/mysql.sql";

// Tables created by sql file (without prefix!)
$modversion['tables'][0] = "".$mydirname."_listing";
$modversion['tables'][1] = "".$mydirname."_categories";

// Search
$modversion['hasSearch'] = 1;
$modversion['search']['file'] = "include/search.inc.php";
$modversion['search']['func'] = "".$mydirname."_search";


//	Module Configs
// $xoopsModuleConfig['usecat']
$modversion['config'][] = array(
'name' => "".$mydirname."_usecat" ,
'title' => '_MI_ALUMNI_USECAT' ,
'description' => '' ,
'formtype' => 'yesno' ,
'valuetype' => 'int' ,
'default' => '1' ,
'options' => array()
) ;

// $xoopsModuleConfig['moderated']
$modversion['config'][] = array(
'name' => "".$mydirname."_moderated" ,
'title' => '_MI_ALUMNI_MODERAT' ,
'description' => '' ,
'formtype' => 'yesno' ,
'valuetype' => 'int' ,
'default' => '0' ,
'options' => array()
) ;

// $xoopsModuleConfig['per_page']
$modversion['config'][] = array(
'name' => "".$mydirname."_per_page" ,
'title' => '_MI_ALUMNI_PERPAGE' ,
'description' => '' ,
'formtype' => 'select' ,
'valuetype' => 'int' ,
'default' => '10' ,
'options' => array('10'=>10, '15'=>15, '20'=>20, '25'=>25, '30'=>30, '35'=>35, '40'=>40, '50'=>50)
) ;

// $xoopsModuleConfig['new_listing']
$modversion['config'][] = array(
'name' => "".$mydirname."_new_listing" ,
'title' => '_MI_ALUMNI_VIEWNEWCLASS' ,
'description' => '_MI_ALUMNI_ONHOME' ,
'formtype' => 'yesno' ,
'valuetype' => 'int' ,
'default' => '1' ,
'options' => array()
) ;

// $xoopsModuleConfig['newalumni']
$modversion['config'][] = array(
'name' => "".$mydirname."_newalumni" ,
'title' => '_MI_ALUMNI_NUMNEW' ,
'description' => '_MI_ALUMNI_ONHOME' ,
//	'formtype' => 'select' ,
'formtype' => 'textbox' ,
'valuetype' => 'int' ,
'default' => '10' ,
//	'options' => array('5'=>5, '10'=>10, '15'=>15, '20'=>20, '25'=>25, '30'=>30, '35'=>35, '40'=>40, '50'=>50)
'options' => array()
) ;

// $xoopsModuleConfig['countday']
$modversion['config'][] = array(
'name' => "".$mydirname."_countday" ,
'title' => '_MI_ALUMNI_NEWTIME' ,
'description' => '_MI_ALUMNI_INDAYS' ,
'formtype' => 'textbox' ,
'valuetype' => 'int' ,
'default' => '3' ,
'options' => array()
) ;

// $xoopsModuleConfig['photomax']
$modversion['config'][] = array(
'name' => "".$mydirname."_photomax" ,
'title' => '_MI_ALUMNI_MAXIIMGS' ,
'description' => '_MI_ALUMNI_INBYTES' ,
'formtype' => 'textbox' ,
'valuetype' => 'int' ,
'default' => '30000' ,
'options' => array()
) ;

// $xoopsModuleConfig['maxwide']
$modversion['config'][] = array(
'name' => "".$mydirname."_maxwide" ,
'title' => '_MI_ALUMNI_MAXWIDE' ,
'description' => '_MI_ALUMNI_INPIXEL' ,
'formtype' => 'textbox' ,
'valuetype' => 'int' ,
'default' => '500' ,
'options' => array()
) ;

// $xoopsModuleConfig['maxhigh']
$modversion['config'][] = array(
'name' => "".$mydirname."_maxhigh" ,
'title' => '_MI_ALUMNI_MAXHIGH' ,
'description' => '_MI_ALUMNI_INPIXEL' ,
'formtype' => 'textbox' ,
'valuetype' => 'int' ,
'default' => '400' ,
'options' => array()
) ;

// $xoopsModuleConfig['type_block']
$modversion['config'][] = array(
'name' => "".$mydirname."_type_block" ,
'title' => '_MI_ALUMNI_TYPEBLOC' ,
'description' => '' ,
'formtype' => 'select' ,
'valuetype' => 'text' ,
'default' => '1' ,
'options' => array('_MI_ALUMNI_LASTTEN'=>'1', '_MI_ALUMNI_JOBRAND'=>'2')
) ;

// $xoopsModuleConfig['disp_cat']
$modversion['config'][] = array(
'name' => "".$mydirname."_disp_cat",
'title' => '_MI_ALUMNI_DISPLSUBCAT',
'description' => '_MI_ALUMNI_ONHOME',
'formtype' => 'yesno',
'valuetype' => 'int',
'default' => '1',
'options' => array()
) ;

// $xoopsModuleConfig['nbsubcat']
$modversion['config'][] = array(
'name' => "".$mydirname."_nbsubcat",
'title' => '_MI_ALUMNI_NBDISPLSUBCAT',
'description' => '',
'formtype' => 'textbox',
'valuetype' => 'int',
'default' => '4',
'options' => array()
) ;

// $xoopsModuleConfig['csortorder']
$modversion['config'][] = array(
'name' => "".$mydirname."_csortorder",
'title' => '_MI_ALUMNI_ORDER',
'description' => '',
'formtype' => 'select',
'valuetype' => 'text',
'default' => 'title',
'options' => array('_MI_ALUMNI_ORDREALPHA'=>'title', '_MI_ALUMNI_ORDREPERSO'=>'ordre' )
) ;

// $xoopsModuleConfig['lsortorder']
$modversion['config'][] = array(
'name' => "".$mydirname."_lsortorder",
'title' => '_MI_ALUMNI_AORDER',
'description' => '',
'formtype' => 'select',
'valuetype' => 'text',
'default' => 'name',
'options' => array("_MI_ALUMNI_ORDER_DATE"=>'date DESC', "_MI_ALUMNI_ORDER_NAME"=>'name ASC', "_MI_ALUMNI_ORDER_POP"=>'hits DESC')
);

// Use WYSIWYG Editors? 
$modversion['config'][] = array(
'name' => "".$mydirname."_form_options",
'title' => '_MI_ALUMNI_EDITOR',
'description' => '_MI_ALUMNI_LIST_EDITOR',
'formtype' => 'select',
'valuetype' => 'text',
'default' => 'dhtml',
'options' => array('DHTML Editor' => 'dhtml', 'TextArea Editor' => 'textarea', 'Koivi Editor' => 'koivi', 'FCK Editor' => 'fckeditor',
'TinyMCE Editor' => 'tinymce' )
) ;

// $xoopsModuleConfig['alumni_use_captcha']
$modversion['config'][] = array(
'name' => "".$mydirname."_use_captcha",
'title' => '_MI_ALUMNI_USE_CAPTCHA',
'description' => '_MI_ALUMNI_USE_CAPTCHA_DESC',
'formtype' => 'yesno',
'valuetype' => 'int',
'default' => '1',
'options' => array()
) ;




//Notification
$modversion['hasNotification'] = 1;

$modversion['notification']['lookup_file'] = 'include/notification.inc.php';
$modversion['notification']['lookup_func'] = "".$mydirname."_notify_iteminfo";

//category
$modversion['notification']['category'][1]['name'] = 'category';
$modversion['notification']['category'][1]['title'] = constant($cloned_lang."_CATEGORY_NOTIFY");
$modversion['notification']['category'][1]['description'] = constant($cloned_lang."_CATEGORY_NOTIFYDSC");
$modversion['notification']['category'][1]['subscribe_from'] = 'index.php';
$modversion['notification']['category'][1]['item_name'] = 'cid';
$modversion['notification']['category'][1]['allow_bookmark'] = 0;
$modversion['notification']['category'][1]['extraParams'] = array('pa');

$modversion['notification']['category'][2]['name'] = 'listing';
$modversion['notification']['category'][2]['title'] = constant($cloned_lang."_NOTIFY");
$modversion['notification']['category'][2]['description'] = constant($cloned_lang."_NOTIFYDSC");
$modversion['notification']['category'][2]['subscribe_from'] = 'index.php';
$modversion['notification']['category'][2]['item_name'] = 'lid';
$modversion['notification']['category'][2]['allow_bookmark'] = 0;
$modversion['notification']['category'][2]['extraParams'] = array('pa');

$modversion['notification']['category'][3]['name'] = 'global';
$modversion['notification']['category'][3]['title'] = constant($cloned_lang."_GLOBAL_NOTIFY");
$modversion['notification']['category'][3]['description'] = constant($cloned_lang."_GLOBAL_NOTIFYDSC");
$modversion['notification']['category'][3]['subscribe_from'] = 'index.php';
$modversion['notification']['category'][3]['extraParams'] = array('pa');

//event
//jobs notifications new listings in this category
$modversion['notification']['event'][1]['name'] = 'new_listing';
$modversion['notification']['event'][1]['category'] = 'category';
$modversion['notification']['event'][1]['title'] = constant($cloned_lang."_NEWPOST_NOTIFY");
$modversion['notification']['event'][1]['caption'] = constant($cloned_lang."_NEWPOST_NOTIFYCAP");
$modversion['notification']['event'][1]['description'] = constant($cloned_lang."_NEWPOST_NOTIFYDSC");
$modversion['notification']['event'][1]['mail_template'] = 'listing_newpost_notify';
$modversion['notification']['event'][1]['mail_subject'] = constant($cloned_lang."_NEWPOST_NOTIFYSBJ");
 
//new listings in all categories posted
$modversion['notification']['event'][2]['name'] = 'new_listing';
$modversion['notification']['event'][2]['category'] = 'global';
$modversion['notification']['event'][2]['title'] = constant($cloned_lang."_GLOBAL_NEWPOST_NOTIFY");
$modversion['notification']['event'][2]['caption'] = constant($cloned_lang."_GLOBAL_NEWPOST_NOTIFYCAP");
$modversion['notification']['event'][2]['description'] = constant($cloned_lang."_GLOBAL_NEWPOST_NOTIFYDSC");
$modversion['notification']['event'][2]['mail_template'] = 'listing_newpost_notify';
$modversion['notification']['event'][2]['mail_subject'] = constant($cloned_lang."_GLOBAL_NEWPOST_NOTIFYSBJ");



// On Update
if( ! empty( $_POST['fct'] ) && ! empty( $_POST['op'] ) && $_POST['fct'] == 'modulesadmin' && $_POST['op'] == 'update_ok' && $_POST['dirname'] == $modversion['dirname'] ) {
	include dirname( __FILE__ ) . "/include/onupdate.inc.php" ;
}

?>